version: '3'
services:
  master:
    image: redis:3
    network_mode: "host"
    command: redis-server --port 6380
    ports:
      - "6380:6379"

  slave1:
    image: redis:3
    command: redis-server --port 6381 --slaveof 192.168.99.100 6380
    network_mode: "host"
    ports:
      - "6381:6379"
    # links:
    #   - master:redis-master

  slave2:
    image: redis:3
    command: redis-server --port 6382 --slaveof 192.168.99.100 6380
    network_mode: "host"
    ports:
      - "6382:6379"
    # links:
    #   - master:redis-master

  sentinel1:
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
      - SENTINEL_PORT=26391
      - REDIS_PORT=26381
    expose:
      - "26391"
    ports:
      - "6391:6379"
      - "26391:26391"
    network_mode: "host"
    # links:
    #   - master:redis-master
    #   - slave1:slave

  sentinel2:
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
      - SENTINEL_PORT=26392
      - REDIS_PORT=26382
    expose:
      - "26392"
    ports:
      - "6392:6379"
      - "26392:26392"
    network_mode: "host"
    # links:
    #   - master:redis-master
    #   - slave1:slave

  sentinel3:
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
      - SENTINEL_PORT=26393
      - REDIS_PORT=26383
    expose:
      - "26393"
    ports:
      - "6393:6379"
      - "26393:26393"
    network_mode: "host"
    # links:
    #   - master:redis-master
    #   - slave1:slave
