version: '3'
services:
  master:
    image: redis:3
    ports:
      - "6380:6379"

  slave1:
    image: redis:3
    command: redis-server --slaveof redis-master 6379
    ports:
      - "6381:6379"
    links:
      - master:redis-master

  slave2:
    image: redis:3
    command: redis-server --slaveof redis-master 6379
    ports:
      - "6382:6379"
    links:
      - master:redis-master

  sentinel1:
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
      - SENTINEL_PORT=26391
    expose:
      - "26391"
    ports:
      - "6391:6379"
      - "26391:26391"
    links:
      - master:redis-master
      - slave1:slave

  sentinel2:
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
      - SENTINEL_PORT=26392
    expose:
      - "26392"
    ports:
      - "6392:6379"
      - "26392:26392"
    links:
      - master:redis-master
      - slave1:slave

  sentinel3:
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
      - SENTINEL_PORT=26393
    expose:
      - "26393"
    ports:
      - "6393:6379"
      - "26393:26393"
    links:
      - master:redis-master
      - slave1:slave
